export interface Series {
  id: string
  name: string
  slug: string
  description?: string
}

export interface Division {
  id: string
  seriesId: string
  name: string
  displayOrder: number
}

export interface Tournament {
  id: string
  name: string
  category?: string        // display category (e.g., "Primera División")
  seriesId?: string
  divisionId?: string
  season: string
  format: "league" | "elimination" | "groups"
  startDate?: string
  endDate?: string
  /** Team that won it (counts as a title on the team page) */
  championTeamId?: string
}

export interface Team {
  id: string
  name: string
  shortName: string
  shield: string
  category?: string        // display category (e.g., "Primera División")
  seriesId?: string
  divisionId?: string
  coach: string
  assistantCoach?: string
  tournamentId?: string
}

/** A team (club) entered in a tournament; the tournament gives series, division and season. */
export interface Registration {
  id: string
  tournamentId: string
  teamId: string
  /** Set when the team left the tournament (pending matches became W.O.) */
  withdrawnAt?: string
}

export interface Player {
  id: string
  name: string
  number: number
  position: "arquero" | "defensa" | "mediocampista" | "delantero"
  photo?: string
  teamId: string
  active: boolean
}

export interface Match {
  id: string
  homeTeamId: string
  awayTeamId: string
  date: string
  time: string
  homeScore?: number
  awayScore?: number
  /** postponed = suspendido (se reprograma), cancelled = no se juega; ninguno cuenta en la tabla */
  status: "scheduled" | "ongoing" | "finished" | "postponed" | "cancelled"
  matchday: number
  tournamentId: string
  venue?: string
  /** Won by W.O. (always 3-0) */
  walkover?: boolean
  /** Public note, e.g. "Suspendido por lluvia" */
  notes?: string
  /** Referee assigned (profile id): can fill in the live sheet */
  refereeId?: string
  /** While ongoing: 1T, ET (entretiempo) or 2T */
  livePeriod?: "1T" | "ET" | "2T"
}

/** One line of the live sheet; score, scorers and cards are derived from these. */
export interface MatchEvent {
  id: string
  matchId: string
  teamId: string
  playerId?: string
  /** Goals only: who gave the pass */
  assistPlayerId?: string
  /** blue: futsal, the player leaves the match without a later suspension */
  type: "goal" | "own_goal" | "yellow" | "red" | "blue"
  period?: "1T" | "2T"
  createdAt: string
}

export interface LeagueSettings {
  /** Yellow cards in a tournament that trigger a suspension; 0 = never */
  yellowCardsForSuspension: number
  /** Matches of suspension for that accumulation */
  yellowSuspensionMatches: number
  /** Matches of suspension for a red card */
  redCardMatches: number
  /** Refuerzos: players not on the lista de buena fe may play */
  guestPlayersAllowed: boolean
  /** Matches per tournament a refuerzo may play; 0 = no limit */
  guestPlayerMaxMatches: number
  /** Days after a finished match its referee can still edit it; null = no limit */
  refereeEditDays: number | null
  /** Futsal blue card on the referee sheet */
  blueCardsEnabled: boolean
}

export interface Sanction {
  id: string
  playerId: string
  matchId?: string
  /** accumulation = suspension generated by too many yellows */
  cardType: "yellow" | "red" | "accumulation"
  matchDate: string
  matchesSuspended: number
  expiresAfterMatch?: number
}

export interface NewsArticle {
  id: string
  title: string
  excerpt: string
  content: string
  image: string
  date: string
  category: string
  seriesId?: string
  /** Match the article is about: its result is shown with the story */
  matchId?: string
  published?: boolean
}

export interface LeagueInfo {
  name: string
  description: string
  currentSeason: string
  ctaText: string
  ctaHref: string
}

export interface PaginatedResult<T> {
  data: T[]
  total: number
  page: number
  totalPages: number
  error: string | null
}

export interface Sponsor {
  id: string
  name: string
  logoUrl: string
  linkUrl?: string
  displayOrder: number
}

export interface PhotoAlbum {
  id: string
  title: string
  description?: string
  date: string
  /** null = whole league */
  seriesId?: string
  /** Optional: the album then shows on both teams' pages */
  matchId?: string
  coverUrl?: string
  published: boolean
  photoCount: number
}

export interface Photo {
  id: string
  albumId: string
  /** Full size (≤2000px) for the viewer */
  url: string
  /** 480px thumbnail for grids */
  thumbUrl?: string
  caption?: string
  displayOrder: number
}
