-- Removes ONLY the mock data from supabase/mock/seed.sql: rows whose id starts
-- with d0d0 and the @mock.liga referee accounts. Real data is not touched.
-- Run it in the Supabase SQL Editor.
begin;

-- Derived from the mock matches (ids generated by the DB)
delete from public.goals where match_id in (select id from public.matches where id::text like 'd0d0%');
delete from public.sanctions where match_id in (select id from public.matches where id::text like 'd0d0%');

delete from public.photos where id::text like 'd0d0%';
delete from public.photo_albums where id::text like 'd0d0%';
delete from public.news_articles where id::text like 'd0d0%';
delete from public.match_events where id::text like 'd0d0%';
delete from public.matches where id::text like 'd0d0%';
delete from public.registration_players where registration_id in (select id from public.registrations where id::text like 'd0d0%');
delete from public.registrations where id::text like 'd0d0%';
delete from public.team_season_photos where id::text like 'd0d0%';
delete from public.players where id::text like 'd0d0%';
delete from public.teams where id::text like 'd0d0%';
delete from public.tournaments where id::text like 'd0d0%';
delete from public.sponsors where id::text like 'd0d0%';

-- Mock referees: profile first (no cascade from auth.users)
delete from public.profiles where id::text like 'd0d0%' and email like '%@mock.liga';
delete from auth.users where id::text like 'd0d0%' and email like '%@mock.liga';

commit;
